<?xml version="1.0" encoding="utf-8"?><Database Name="Aguas" Class="DcAguasDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=DESKTOP-DJ6301P;Initial Catalog=Aguas;Integrated Security=True" SettingsObjectName="ProjetoAguas.Properties.Settings" SettingsPropertyName="AguasConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="Cliente.Clientes" Member="Clientes">
    <Type Name="Clientes">
      <Column Name="IdCliente" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Nome" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Telefone" Type="System.String" DbType="VarChar(12) NOT NULL" CanBeNull="false" />
      <Column Name="NIF" Type="System.String" DbType="VarChar(9) NOT NULL" CanBeNull="false" />
      <Column Name="Email" Type="System.String" DbType="VarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="Morada" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="CodigoPostal" Type="System.String" DbType="VarChar(8) NOT NULL" CanBeNull="false" />
      <Column Name="ModificacaoData" Type="System.DateTime" DbType="DateTime2 NOT NULL" CanBeNull="false" />
      <Association Name="Cliente_Contrato" Member="Contratos" ThisKey="IdCliente" OtherKey="IdCliente" Type="Contratos" />
    </Type>
  </Table>
  <Table Name="Contrato.Contratos" Member="Contratos">
    <Type Name="Contratos">
      <Column Name="IdContrato" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="IdCliente" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="DataContrato" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="TipoContrato" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="TipoPagamento" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="Morada" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="CodigoPostal" Type="System.String" DbType="VarChar(8) NOT NULL" CanBeNull="false" />
      <Column Name="ModificacaoData" Type="System.DateTime" DbType="DateTime2 NOT NULL" CanBeNull="false" />
      <Association Name="Contrato_Consumo" Member="Consumos" ThisKey="IdContrato" OtherKey="IdContrato" Type="Consumos" />
      <Association Name="Cliente_Contrato" Member="Clientes" ThisKey="IdCliente" OtherKey="IdCliente" Type="Clientes" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="Contrato.Faturas" Member="Faturas">
    <Type Name="Faturas">
      <Column Name="IdFatura" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="IdContrato" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="DataFatura" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Cliente" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="ConsumoMensal" Type="System.Decimal" DbType="Decimal(5,2) NOT NULL" CanBeNull="false" />
      <Column Name="ValorPagar" Type="System.Decimal" DbType="Decimal(7,2) NOT NULL" CanBeNull="false" />
      <Column Name="ModificacaoData" Type="System.DateTime" DbType="DateTime2 NOT NULL" CanBeNull="false" />
      <Association Name="Fatura_Consumo" Member="Consumos" ThisKey="IdFatura" OtherKey="IdFatura" Type="Consumos" />
    </Type>
  </Table>
  <Table Name="Leitura.Consumos" Member="Consumos">
    <Type Name="Consumos">
      <Column Name="IdConsumo" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="IdContrato" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="IdFatura" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Escaloes" Type="System.Decimal" DbType="Decimal(5,2) NOT NULL" CanBeNull="false" />
      <Column Name="ValorUnitario" Type="System.Decimal" DbType="Decimal(5,2) NOT NULL" CanBeNull="false" />
      <Column Name="DataConsumo" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="ConsumoTotal" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="ModificacaoData" Type="System.DateTime" DbType="DateTime2 NOT NULL" CanBeNull="false" />
      <Association Name="Contrato_Consumo" Member="Contratos" ThisKey="IdContrato" OtherKey="IdContrato" Type="Contratos" IsForeignKey="true" />
      <Association Name="Fatura_Consumo" Member="Faturas" ThisKey="IdFatura" OtherKey="IdFatura" Type="Faturas" IsForeignKey="true" />
    </Type>
  </Table>
</Database>